export const COMMENTS = 
[
    {
        id: 0,
        vehicleId: 0,
        date: "2018-10-25",
        text: "Car needed an oil Change!",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 1,
        vehicleId: 0,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 2,
        vehicleId: 0, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 3,
        vehicleId: 0,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 4,
        vehicleId: 0,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 5,
        vehicleId: 1, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 6,
        vehicleId: 1, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 7,
        vehicleId: 1, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 8,
        vehicleId: 1,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 9,
        vehicleId: 1, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 10,
        vehicleId: 2,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 11,
        vehicleId: 2,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 12,
        vehicleId: 2, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 13,
        vehicleId: 2, 
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    },
    {
        id: 14,
        vehicleId: 2,
        date: "2017-06-17",
        text: "Rotated Tires. Found a small leak in radiator. radiator got replaced. ",
        nextServiceDay: "1-25-2019",
    }
]