export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
// export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_ADD_COMMENT = "EDIT_ADD_COMMENT";

export const COMMENTS_FAILED = "COMMENTS_FAILED";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const ADD_COMMENTS = "ADD_COMMENTS";

export const VEHICLES_LOADING = "VEHICLES_LOADING";
export const VEHICLES_FAILED = "VEHICLES_FAILED";
export const ADD_VEHICLES = "ADD_VEHICLES";
export const POST_NEW_VEHICLE = "POST_NEW_VEHICLE";

export const ADD_VEHICLE = "ADD_VEHICLE";
